### ISSUE TITLE
Feature Request: Line Numbers

### ISSUE THREAD

**Issue by djmtype** [Mokkapps/nuxt-content-v2-custom-code-blocks#1]
It would be great to include a line numbers option.

**Comment by Mokkapps** [comment]
Done:

![image](https://user-images.githubusercontent.com/3127210/174550721-36fd8666-b713-4973-addf-7303dee50c25.png)

Corresponding code changes:

```css
:slotted(pre) {
  counter-reset: lines;
}

:slotted(pre code .line::before) {
  counter-increment: lines;
  content: counter(lines);
  width: 1rem;
  margin-right: 1.5rem;
  display: inline-block;
  text-align: left;
  color: rgba(115, 138, 148, 0.4);
}
```
